<a href="https://colab.research.google.com/github/Shrawanpandit/Machine_Learning_Lab-Works/blob/main/MachineLearning_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```markdown
# Lab Session 2: Working with Dictionary and DataFrame
```

```markdown
## Part I: Working with Dictionary

A data structure used to store data in key-value pairs.
```

In [1]:
# Create a dictionary
student = {
    "name": "Ram",
    "age": 20,
    "faculty": "BCE"
}
display(f"Initial Dictionary: {student}")

d = {"a": 1, "b": 2}
display(f"New Dictionary d: {d}")

"Initial Dictionary: {'name': 'Ram', 'age': 20, 'faculty': 'BCE'}"

"New Dictionary d: {'a': 1, 'b': 2}"

In [2]:
# Access Value
display(f"Accessing 'name' from student: {student['name']}")

# Use get()
display(f"Using get() for 'age' from student: {student.get('age')}")
display(f"Using get() for non-existent key 'gender': {student.get('gender')}")

"Accessing 'name' from student: Ram"

"Using get() for 'age' from student: 20"

"Using get() for non-existent key 'gender': None"

In [3]:
# Add Item
student["grade"] = "A"
display(f"Dictionary after adding 'grade': {student}")
d['c'] = 3
display(f"Dictionary d after adding 'c': {d}")

"Dictionary after adding 'grade': {'name': 'Ram', 'age': 20, 'faculty': 'BCE', 'grade': 'A'}"

"Dictionary d after adding 'c': {'a': 1, 'b': 2, 'c': 3}"

In [4]:
# Update Value
student["age"] = 21
display(f"Dictionary after updating 'age': {student}")
d["a"] = 10
display(f"Dictionary d after updating 'a': {d}")

"Dictionary after updating 'age': {'name': 'Ram', 'age': 21, 'faculty': 'BCE', 'grade': 'A'}"

"Dictionary d after updating 'a': {'a': 10, 'b': 2, 'c': 3}"

In [5]:
# Remove Item using del
if "faculty" in student:
    del student["faculty"]
display(f"Dictionary after deleting 'faculty': {student}")

if "b" in d:
    del d["b"]
display(f"Dictionary d after deleting 'b': {d}")

"Dictionary after deleting 'faculty': {'name': 'Ram', 'age': 21, 'grade': 'A'}"

"Dictionary d after deleting 'b': {'a': 10, 'c': 3}"

In [6]:
# Remove using pop()
popped_grade = student.pop("grade")
display(f"Popped 'grade': {popped_grade}, Dictionary: {student}")

popped_a = d.pop("a")
display(f"Popped 'a': {popped_a}, Dictionary d: {d}")

"Popped 'grade': A, Dictionary: {'name': 'Ram', 'age': 21}"

"Popped 'a': 10, Dictionary d: {'c': 3}"

In [7]:
# Remove Last Item d.popitem()
if student: # Ensure dictionary is not empty
    popped_item = student.popitem()
    display(f"Popped last item: {popped_item}, Dictionary: {student}")
else:
    display("Student dictionary is empty, cannot popitem.")

if d: # Ensure dictionary is not empty
    popped_item_d = d.popitem()
    display(f"Popped last item from d: {popped_item_d}, Dictionary d: {d}")
else:
    display("Dictionary d is empty, cannot popitem.")

"Popped last item: ('age', 21), Dictionary: {'name': 'Ram'}"

"Popped last item from d: ('c', 3), Dictionary d: {}"

In [8]:
# Copy Dictionary
original_d = {"x": 10, "y": 20}
new_d = original_d.copy()
display(f"Original dictionary for copy: {original_d}")
display(f"Copied dictionary new_d: {new_d}")

# Modify new_d to show it's a separate copy
new_d["z"] = 30
display(f"Modified new_d: {new_d}")
display(f"Original d remains unchanged: {original_d}")

"Original dictionary for copy: {'x': 10, 'y': 20}"

"Copied dictionary new_d: {'x': 10, 'y': 20}"

"Modified new_d: {'x': 10, 'y': 20, 'z': 30}"

"Original d remains unchanged: {'x': 10, 'y': 20}"

In [9]:
# Reinitialize student dictionary for further operations
student = {
    "name": "Ram",
    "age": 20,
    "faculty": "BCE",
    "grade": "A"
}
display(f"Reinitialized student dictionary: {student}")

# Get All Keys
display(f"All keys: {student.keys()}")

# Get All Values
display(f"All values: {student.values()}")

# Get All Items
display(f"All items: {student.items()}")

"Reinitialized student dictionary: {'name': 'Ram', 'age': 20, 'faculty': 'BCE', 'grade': 'A'}"

"All keys: dict_keys(['name', 'age', 'faculty', 'grade'])"

"All values: dict_values(['Ram', 20, 'BCE', 'A'])"

"All items: dict_items([('name', 'Ram'), ('age', 20), ('faculty', 'BCE'), ('grade', 'A')])"

In [10]:
# Check Key Exists
display(f"Is 'name' in student? {'name' in student}")
display(f"Is 'address' in student? {'address' in student}")

"Is 'name' in student? True"

"Is 'address' in student? False"

In [11]:
# Get Length
display(f"Length of student dictionary: {len(student)}")

'Length of student dictionary: 4'

In [12]:
# Loop Through Keys
display("Looping through keys:")
for k in student:
    display(k)

# Loop Through Values
display("Looping through values:")
for v in student.values():
    display(v)

# Loop Through Items
display("Looping through items:")
for k, v in student.items():
    display(f"{k}: {v}")

'Looping through keys:'

'name'

'age'

'faculty'

'grade'

'Looping through values:'

'Ram'

20

'BCE'

'A'

'Looping through items:'

'name: Ram'

'age: 20'

'faculty: BCE'

'grade: A'

```markdown
## Part II: Working with Pandas DataFrame

A DataFrame in Python is a two-dimensional, tabular data structure that organizes data into labeled rows and columns. It is conceptually identical to an Excel spreadsheet or a SQL table, making it the primary tool for data manipulation and analysis in the Pandas Library.
```

In [13]:
import pandas as pd

# Create a DataFrame containing student details
data = {
    'Name': ['Ram', 'Shyam', 'Hari', 'Sita', 'Gita'],
    'Age': [20, 22, 19, 21, 23],
    'Marks': [85, 78, 92, 65, 88]
}
df = pd.DataFrame(data)

display("Created DataFrame:")
display(df)

'Created DataFrame:'

    Name  Age  Marks
0    Ram   20     85
1  Shyam   22     78
2   Hari   19     92
3   Sita   21     65
4   Gita   23     88

In [14]:
# Display the first 5 rows of the DataFrame.
display("First 5 rows:")
display(df.head())

'First 5 rows:'

    Name  Age  Marks
0    Ram   20     85
1  Shyam   22     78
2   Hari   19     92
3   Sita   21     65
4   Gita   23     88

In [15]:
# Display the last 5 rows of the DataFrame.
display("Last 5 rows:")
display(df.tail())

'Last 5 rows:'

    Name  Age  Marks
0    Ram   20     85
1  Shyam   22     78
2   Hari   19     92
3   Sita   21     65
4   Gita   23     88

In [16]:
# Find the total number of rows and columns in the DataFrame.
display("Shape (rows, columns):")
display(df.shape)

'Shape (rows, columns):'

(5, 3)

In [17]:
# Display all column names in the DataFrame.
display("Column names:")
display(df.columns)

'Column names:'

Index(['Name', 'Age', 'Marks'], dtype='object')

In [18]:
# Display complete information about the DataFrame including data types and memory usage.
display("DataFrame Info:")
df.info()

'DataFrame Info:'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [19]:
# Generate a statistical summary of numerical columns in the DataFrame.
display("Statistical Summary:")
display(df.describe())

'Statistical Summary:'

             Age      Marks
count   5.000000   5.000000
mean   21.000000  81.600000
std     1.581139  10.597169
min    19.000000  65.000000
25%    20.000000  78.000000
50%    21.000000  85.000000
75%    22.000000  88.000000
max    23.000000  92.000000

In [20]:
# Select and display the Name column from the DataFrame.
display("Name column:")
display(df['Name'])

'Name column:'

0      Ram
1    Shyam
2     Hari
3     Sita
4     Gita
Name: Name, dtype: object

In [21]:
# Select and display multiple columns such as Name and Marks.
display("Name and Marks columns:")
display(df[['Name', 'Marks']])

'Name and Marks columns:'

    Name  Marks
0    Ram     85
1  Shyam     78
2   Hari     92
3   Sita     65
4   Gita     88

In [22]:
# Display the first row of the DataFrame using positional indexing.
display("First row using iloc:")
display(df.iloc[0])

'First row using iloc:'

Name     Ram
Age       20
Marks     85
Name: 0, dtype: object

In [23]:
# Display the first row of the DataFrame using label-based indexing.
display("First row using loc:")
display(df.loc[0])

'First row using loc:'

Name     Ram
Age       20
Marks     85
Name: 0, dtype: object

In [24]:
# Access a specific cell value such as Marks of the first student.
display("Marks of the first student (Ram):")
display(df.loc[0, 'Marks'])

'Marks of the first student (Ram):'

np.int64(85)

In [25]:
# Filter and display students whose Marks are greater than 80.
display("Students with Marks > 80:")
display(df[df['Marks'] > 80])

'Students with Marks > 80:'

   Name  Age  Marks
0   Ram   20     85
2  Hari   19     92
4  Gita   23     88

In [26]:
# Filter and display students whose Age is greater than 20 and Marks are greater than 75.
display("Students with Age > 20 AND Marks > 75:")
display(df[(df['Age'] > 20) & (df['Marks'] > 75)])

'Students with Age > 20 AND Marks > 75:'

    Name  Age  Marks
1  Shyam   22     78
4   Gita   23     88

In [27]:
# Add a new column called Grade to the DataFrame.
# Ensure the length of the list matches the number of rows
df['Grade'] = ['A', 'B', 'A', 'C', 'A']
display("DataFrame after adding 'Grade' column:")
display(df)

"DataFrame after adding 'Grade' column:"

    Name  Age  Marks Grade
0    Ram   20     85     A
1  Shyam   22     78     B
2   Hari   19     92     A
3   Sita   21     65     C
4   Gita   23     88     A

In [28]:
# Increase all students’ Marks by 5.
df['Marks'] = df['Marks'] + 5
display("DataFrame after increasing Marks by 5:")
display(df)

'DataFrame after increasing Marks by 5:'

    Name  Age  Marks Grade
0    Ram   20     90     A
1  Shyam   22     83     B
2   Hari   19     97     A
3   Sita   21     70     C
4   Gita   23     93     A

In [29]:
# Update the Marks of Ram to 95 using a condition.
df.loc[df['Name'] == 'Ram', 'Marks'] = 95
display("DataFrame after updating Ram's Marks to 95:")
display(df)

"DataFrame after updating Ram's Marks to 95:"

    Name  Age  Marks Grade
0    Ram   20     95     A
1  Shyam   22     83     B
2   Hari   19     97     A
3   Sita   21     70     C
4   Gita   23     93     A

In [30]:
# Remove the Age column from the DataFrame.
df_no_age = df.drop('Age', axis=1)
display("DataFrame after removing 'Age' column (original df is unchanged unless reassigned):")
display(df_no_age)
# Note: df.drop returns a new DataFrame; the original df remains unchanged unless reassigned
display("Original DataFrame (Age column still exists):")
display(df)

"DataFrame after removing 'Age' column (original df is unchanged unless reassigned):"

    Name  Marks Grade
0    Ram     95     A
1  Shyam     83     B
2   Hari     97     A
3   Sita     70     C
4   Gita     93     A

'Original DataFrame (Age column still exists):'

    Name  Age  Marks Grade
0    Ram   20     95     A
1  Shyam   22     83     B
2   Hari   19     97     A
3   Sita   21     70     C
4   Gita   23     93     A

In [31]:
# Remove the first row from the DataFrame.
df_no_first_row = df.drop(0, axis=0)
display("DataFrame after removing the first row (original df is unchanged unless reassigned):")
display(df_no_first_row)

'DataFrame after removing the first row (original df is unchanged unless reassigned):'

    Name  Age  Marks Grade
1  Shyam   22     83     B
2   Hari   19     97     A
3   Sita   21     70     C
4   Gita   23     93     A

In [32]:
# Sort the DataFrame by Marks in ascending order.
display("DataFrame sorted by Marks (ascending):")
display(df.sort_values('Marks'))

'DataFrame sorted by Marks (ascending):'

    Name  Age  Marks Grade
3   Sita   21     70     C
1  Shyam   22     83     B
4   Gita   23     93     A
0    Ram   20     95     A
2   Hari   19     97     A

In [33]:
# Sort the DataFrame by Marks in descending order.
display("DataFrame sorted by Marks (descending):")
display(df.sort_values('Marks', ascending=False))

'DataFrame sorted by Marks (descending):'

    Name  Age  Marks Grade
2   Hari   19     97     A
0    Ram   20     95     A
4   Gita   23     93     A
1  Shyam   22     83     B
3   Sita   21     70     C

In [34]:
# Concatenate two DataFrames vertically.
data2 = {
    'Name': ['Prem', 'Laxmi'],
    'Age': [24, 25],
    'Marks': [70, 90],
    'Grade': ['B', 'A']
}
df2 = pd.DataFrame(data2)

display("Second DataFrame to concatenate:")
display(df2)

df_concatenated = pd.concat([df, df2])
display("Concatenated DataFrame:")
display(df_concatenated)

'Second DataFrame to concatenate:'

    Name  Age  Marks Grade
0   Prem   24     70     B
1  Laxmi   25     90     A

'Concatenated DataFrame:'

    Name  Age  Marks Grade
0    Ram   20     95     A
1  Shyam   22     83     B
2   Hari   19     97     A
3   Sita   21     70     C
4   Gita   23     93     A
0   Prem   24     70     B
1  Laxmi   25     90     A

In [35]:
# Read data from a CSV file into a DataFrame.
# First, let's save our current DataFrame to a CSV to demonstrate reading it back.
df.to_csv('students.csv', index=False)
display("DataFrame saved to students.csv. Now reading it back:")

df_from_csv = pd.read_csv('students.csv')
display(df_from_csv)

'DataFrame saved to students.csv. Now reading it back:'

    Name  Age  Marks Grade
0    Ram   20     95     A
1  Shyam   22     83     B
2   Hari   19     97     A
3   Sita   21     70     C
4   Gita   23     93     A

In [36]:
# Write the DataFrame into a CSV file.
# This was already demonstrated in the previous step, but explicitly here:
df_concatenated.to_csv('all_students.csv', index=False)
display("Concatenated DataFrame saved to all_students.csv.")
# You can check the file in the Colab file browser.

'Concatenated DataFrame saved to all_students.csv.'

In [37]:
# Read data from an Excel file into a DataFrame.
# First, let's save our current DataFrame to an Excel to demonstrate reading it back.
# You might need to install openpyxl if not already present:
# !pip install openpyxl
df.to_excel('students.xlsx', index=False)
display("DataFrame saved to students.xlsx. Now reading it back:")

df_from_excel = pd.read_excel('students.xlsx')
display(df_from_excel)

'DataFrame saved to students.xlsx. Now reading it back:'

    Name  Age  Marks Grade
0    Ram   20     95     A
1  Shyam   22     83     B
2   Hari   19     97     A
3   Sita   21     70     C
4   Gita   23     93     A

In [38]:
# Write the DataFrame into an Excel file.
# This was already demonstrated in the previous step, but explicitly here:
df_concatenated.to_excel('all_students.xlsx', index=False)
display("Concatenated DataFrame saved to all_students.xlsx.")
# You can check the file in the Colab file browser.

'Concatenated DataFrame saved to all_students.xlsx.'